#ifndef XM_QMESSDEF_H_
 
/*
 * 
 * Automatically generated by GENMSGINC
 * 
 * Configuration: XCC,SYS,XMPY
 * Option XCC root = /opt/xmopts/xcc
 * Option SYS root = /opt/xmidas/xm
 * Option XMPY root = /opt/xmopts/xmpy
 *
 */
 
#include "queue.h"
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_MSGLOG;
 
#define mqh_MSGLOG_INIT {0,34,'H',15,0,4,0,0,{'M','S','G','L','O','G',' ',' '},16,{'L','S','[','2','4',']','S','[','4','0',']','S','[','8','0',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   int_4	severity;
   char		date_time[24];
   char		source[40];
   char		text[80];
} mqd_MSGLOG;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_XMSG;
 
#define mqh_XMSG_INIT {0,31,'H',15,0,4,0,0,{'X','M','S','G',' ',' ',' ',' '},16,{'L','S','[','2','4',']','S','[','1','6',']','S','[','8','0',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   int_4	severity;
   char		date_time[24];
   char		source[16];
   char		text[80];
} mqd_XMSG;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_TITLE;
 
#define mqh_TITLE_INIT {0,20,'H',15,0,1,0,0,{'T','I','T','L','E',' ',' ',' '},5,{'S','[','4','0',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		text[40];
} mqd_TITLE;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
} mqh_MSGMASK;
 
#define mqh_MSGMASK_INIT {0,5,'L',4,0,1,0,0,{'M','S','G','M','A','S','K',' '}}
 
typedef struct
{
   int_4	mask;
} mqd_MSGMASK;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	msgid;
   int_4	mode;
   char		name[8];
} mqh_MSGMASKINFO;
 
#define mqh_MSGMASKINFO_INIT {0,5,'L',4,0,1,0,0,{'=','M','S','G','M','A','S','K'}}
 
typedef struct
{
   int_4	mask;
} mqd_MSGMASKINFO;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	value;
   int_4	mode;
   char		name[8];
} mqh_SET;
 
#define mqh_SET_INIT {0,5,'A',4,0,1,0,0,{'S','E','T',' ',' ',' ',' ',' '}}
 
typedef struct
{
   char		object[8];
} mqd_SET;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_SETL;
 
#define mqh_SETL_INIT {0,17,'H',15,0,3,0,0,{'S','E','T','L',' ',' ',' ',' '},3,{'A','2','L',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		object[8];
   int_4	value;
   int_4	value2;
} mqd_SETL;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_SETD;
 
#define mqh_SETD_INIT {0,17,'H',15,0,2,0,0,{'S','E','T','D',' ',' ',' ',' '},2,{'A','D',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		object[8];
   real_8	value;
} mqd_SETD;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
} mqh_QUERY;
 
#define mqh_QUERY_INIT {0,5,'A',4,0,1,0,0,{'Q','U','E','R','Y',' ',' ',' '}}
 
typedef struct
{
   char		object[8];
} mqd_QUERY;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
} mqh_EXIT;
 
#define mqh_EXIT_INIT {0,4,' ',4,0,0,0,0,{'E','X','I','T',' ',' ',' ',' '}}
 
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
} mqh_EXITINFO;
 
#define mqh_EXITINFO_INIT {0,4,' ',4,0,0,0,0,{'=','E','X','I','T',' ',' ',' '}}
 
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
} mqh_REREAD;
 
#define mqh_REREAD_INIT {0,4,' ',4,0,0,0,0,{'R','E','R','E','A','D',' ',' '}}
 
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
} mqh_REFRESH;
 
#define mqh_REFRESH_INIT {0,4,' ',4,0,0,0,0,{'R','E','F','R','E','S','H',' '}}
 
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	colorid;
   int_4	mode;
   char		name[8];
} mqh_COLOR;
 
#define mqh_COLOR_INIT {0,5,'I',4,0,4,0,0,{'C','O','L','O','R',' ',' ',' '}}
 
typedef struct
{
   int_2	position;
   int_2	red;
   int_2	green;
   int_2	blue;
} mqd_COLOR;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	colorid;
   int_4	mode;
   char		name[8];
} mqh_COLORINFO;
 
#define mqh_COLORINFO_INIT {0,5,'I',4,0,4,0,0,{'=','C','O','L','O','R',' ',' '}}
 
typedef struct
{
   int_2	position;
   int_2	red;
   int_2	green;
   int_2	blue;
} mqd_COLORINFO;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	colormapid;
   int_4	mode;
   char		name[8];
} mqh_COLORMAP;
 
#define mqh_COLORMAP_INIT {0,11,'I',4,0,28,0,0,{'C','O','L','O','R','M','A','P'}}
 
typedef struct
{
   int_2	position1;
   int_2	red1;
   int_2	green1;
   int_2	blue1;
   int_2	position2;
   int_2	red2;
   int_2	green2;
   int_2	blue2;
   int_2	position3;
   int_2	red3;
   int_2	green3;
   int_2	blue3;
   int_2	position4;
   int_2	red4;
   int_2	green4;
   int_2	blue4;
   int_2	position5;
   int_2	red5;
   int_2	green5;
   int_2	blue5;
   int_2	position6;
   int_2	red6;
   int_2	green6;
   int_2	blue6;
   int_2	position7;
   int_2	red7;
   int_2	green7;
   int_2	blue7;
} mqd_COLORMAP;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	colormapid;
   int_4	mode;
   char		name[8];
} mqh_COLORMAPINFO;
 
#define mqh_COLORMAPINFO_INIT {0,11,'I',4,0,28,0,0,{'=','C','O','L','O','R','M','A'}}
 
typedef struct
{
   int_2	position1;
   int_2	red1;
   int_2	green1;
   int_2	blue1;
   int_2	position2;
   int_2	red2;
   int_2	green2;
   int_2	blue2;
   int_2	position3;
   int_2	red3;
   int_2	green3;
   int_2	blue3;
   int_2	position4;
   int_2	red4;
   int_2	green4;
   int_2	blue4;
   int_2	position5;
   int_2	red5;
   int_2	green5;
   int_2	blue5;
   int_2	position6;
   int_2	red6;
   int_2	green6;
   int_2	blue6;
   int_2	position7;
   int_2	red7;
   int_2	green7;
   int_2	blue7;
} mqd_COLORMAPINFO;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	layer;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_TRACE;
 
#define mqh_TRACE_INIT {0,18,'H',15,0,5,0,0,{'T','R','A','C','E',' ',' ',' '},5,{'2','L','A','2','L',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   int_4	linetype;
   int_4	thick;
   char		symbol[8];
   int_4	radius;
   int_4	color;
} mqd_TRACE;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	layer;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_OVERLAY;
 
#define mqh_OVERLAY_INIT {0,25,'H',15,0,1,0,0,{'O','V','E','R','L','A','Y',' '},5,{'S','[','8','0',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		text[80];
} mqd_OVERLAY;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	layer;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_DEOVERLAY;
 
#define mqh_DEOVERLAY_INIT {0,25,'H',15,0,1,0,0,{'D','E','O','V','E','R','L','A'},5,{'S','[','8','0',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		text[80];
} mqd_DEOVERLAY;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	flag;
   int_4	mode;
   char		name[8];
} mqh_TRIM;
 
#define mqh_TRIM_INIT {0,6,'D',4,0,2,0,0,{'T','R','I','M',' ',' ',' ',' '}}
 
typedef struct
{
   real_8	x1;
   real_8	x2;
} mqd_TRIM;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	level;
   int_4	mode;
   char		name[8];
} mqh_CXMODE;
 
#define mqh_CXMODE_INIT {0,5,'A',4,0,1,0,0,{'C','X','M','O','D','E',' ',' '}}
 
typedef struct
{
   char		mode[8];
} mqd_CXMODE;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	level;
   int_4	mode;
   char		name[8];
} mqh_CXMODEINFO;
 
#define mqh_CXMODEINFO_INIT {0,5,'A',4,0,1,0,0,{'=','C','X','M','O','D','E',' '}}
 
typedef struct
{
   char		mode[8];
} mqd_CXMODEINFO;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	level;
   int_4	mode;
   char		name[8];
} mqh_ZOOM;
 
#define mqh_ZOOM_INIT {0,8,'D',4,0,4,0,0,{'Z','O','O','M',' ',' ',' ',' '}}
 
typedef struct
{
   real_8	xmin;
   real_8	xmax;
   real_8	ymin;
   real_8	ymax;
} mqd_ZOOM;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	level;
   int_4	mode;
   char		name[8];
} mqh_ZOOMINFO;
 
#define mqh_ZOOMINFO_INIT {0,8,'D',4,0,4,0,0,{'=','Z','O','O','M',' ',' ',' '}}
 
typedef struct
{
   real_8	xmin;
   real_8	xmax;
   real_8	ymin;
   real_8	ymax;
} mqd_ZOOMINFO;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	level;
   int_4	mode;
   char		name[8];
} mqh_UNZOOM;
 
#define mqh_UNZOOM_INIT {0,4,' ',4,0,0,0,0,{'U','N','Z','O','O','M',' ',' '}}
 
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	level;
   int_4	mode;
   char		name[8];
} mqh_UNZOOMINFO;
 
#define mqh_UNZOOMINFO_INIT {0,8,'D',4,0,4,0,0,{'=','U','N','Z','O','O','M',' '}}
 
typedef struct
{
   real_8	xmin;
   real_8	xmax;
   real_8	ymin;
   real_8	ymax;
} mqd_UNZOOMINFO;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	level;
   int_4	mode;
   char		name[8];
} mqh_PAN;
 
#define mqh_PAN_INIT {0,8,'D',4,0,4,0,0,{'P','A','N',' ',' ',' ',' ',' '}}
 
typedef struct
{
   real_8	xmin;
   real_8	xmax;
   real_8	ymin;
   real_8	ymax;
} mqd_PAN;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
} mqh_PANRANGE;
 
#define mqh_PANRANGE_INIT {0,8,'D',4,0,4,0,0,{'P','A','N','R','A','N','G','E'}}
 
typedef struct
{
   real_8	xmin;
   real_8	xmax;
   real_8	ymin;
   real_8	ymax;
} mqd_PANRANGE;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	level;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_PANINFO;
 
#define mqh_PANINFO_INIT {0,21,'H',15,0,7,0,0,{'=','P','A','N',' ',' ',' ',' '},5,{'4','D','2','L','A',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   real_8	xmin;
   real_8	xmax;
   real_8	ymin;
   real_8	ymax;
   int_4	xunits;
   int_4	yunits;
   char		cxmode[8];
} mqd_PANINFO;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	level;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_PLOTINFO;
 
#define mqh_PLOTINFO_INIT {0,23,'H',15,0,10,0,0,{'=','P','L','O','T',' ',' ',' '},8,{'4','D','2','L','A','2','L','A',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   real_8	xmin;
   real_8	xmax;
   real_8	ymin;
   real_8	ymax;
   int_4	xunits;
   int_4	yunits;
   char		cxmode[8];
   int_4	xframe;
   int_4	yframe;
   char		primname[8];
} mqd_PLOTINFO;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
} mqh_MARKINFO;
 
#define mqh_MARKINFO_INIT {0,7,'D',4,0,3,0,0,{'=','M','A','R','K',' ',' ',' '}}
 
typedef struct
{
   real_8	x;
   real_8	y;
   real_8	z;
} mqd_MARKINFO;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
} mqh_MARK;
 
#define mqh_MARK_INIT {0,7,'D',4,0,3,0,0,{'M','A','R','K',' ',' ',' ',' '}}
 
typedef struct
{
   real_8	x;
   real_8	y;
   real_8	z;
} mqd_MARK;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	anntid;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_ANNOTATE;
 
#define mqh_ANNOTATE_INIT {0,27,'H',15,0,4,0,0,{'A','N','N','O','T','A','T','E'},8,{'A','S','[','8','0',']','2','L',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		func[8];
   char		text[80];
   int_4	arg1;
   int_4	arg2;
} mqd_ANNOTATE;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	boxid;
   int_4	mode;
   char		name[8];
} mqh_BOXINFO;
 
#define mqh_BOXINFO_INIT {0,8,'D',4,0,4,0,0,{'=','B','O','X',' ',' ',' ',' '}}
 
typedef struct
{
   real_8	xmin;
   real_8	xmax;
   real_8	ymin;
   real_8	ymax;
} mqd_BOXINFO;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	boxid;
   int_4	mode;
   char		name[8];
} mqh_BOXADD;
 
#define mqh_BOXADD_INIT {0,8,'D',4,0,4,0,0,{'B','O','X','A','D','D',' ',' '}}
 
typedef struct
{
   real_8	xmin;
   real_8	xmax;
   real_8	ymin;
   real_8	ymax;
} mqd_BOXADD;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	boxid;
   int_4	mode;
   char		name[8];
} mqh_BOXDELETE;
 
#define mqh_BOXDELETE_INIT {0,4,' ',4,0,0,0,0,{'B','O','X','D','E','L','E','T'}}
 
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	boxid;
   int_4	mode;
   char		name[8];
} mqh_BOXALTER;
 
#define mqh_BOXALTER_INIT {0,8,'D',4,0,4,0,0,{'B','O','X','A','L','T','E','R'}}
 
typedef struct
{
   real_8	xmin;
   real_8	xmax;
   real_8	ymin;
   real_8	ymax;
} mqd_BOXALTER;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	pointid;
   int_4	mode;
   char		name[8];
} mqh_POINTINFO;
 
#define mqh_POINTINFO_INIT {0,6,'D',4,0,2,0,0,{'=','P','O','I','N','T',' ',' '}}
 
typedef struct
{
   real_8	x;
   real_8	y;
} mqd_POINTINFO;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	pointid;
   int_4	mode;
   char		name[8];
} mqh_POINTADD;
 
#define mqh_POINTADD_INIT {0,6,'D',4,0,2,0,0,{'P','O','I','N','T','A','D','D'}}
 
typedef struct
{
   real_8	x;
   real_8	y;
} mqd_POINTADD;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	pointid;
   int_4	mode;
   char		name[8];
} mqh_POINTDELETE;
 
#define mqh_POINTDELETE_INIT {0,4,' ',4,0,0,0,0,{'P','O','I','N','T','D','E','L'}}
 
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	pointid;
   int_4	mode;
   char		name[8];
} mqh_POINTALTER;
 
#define mqh_POINTALTER_INIT {0,6,'D',4,0,2,0,0,{'P','O','I','N','T','A','L','T'}}
 
typedef struct
{
   real_8	x;
   real_8	y;
} mqd_POINTALTER;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	awid;
   int_4	mode;
   char		name[8];
} mqh_XCNTRL;
 
#define mqh_XCNTRL_INIT {0,5,'D',4,0,1,0,0,{'X','C','N','T','R','L',' ',' '}}
 
typedef struct
{
   real_8	value;
} mqd_XCNTRL;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	rwid;
   int_4	mode;
   char		name[8];
} mqh_XCTAG;
 
#define mqh_XCTAG_INIT {0,5,'D',4,0,1,0,0,{'X','C','T','A','G',' ',' ',' '}}
 
typedef struct
{
   real_8	value;
} mqd_XCTAG;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
} mqh_XTODO;
 
#define mqh_XTODO_INIT {0,5,'D',4,0,1,0,0,{'X','T','O','D','O',' ',' ',' '}}
 
typedef struct
{
   real_8	amount;
} mqd_XTODO;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	flag;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_HARDCOPY;
 
#define mqh_HARDCOPY_INIT {0,25,'H',15,0,1,0,0,{'H','A','R','D','C','O','P','Y'},5,{'S','[','8','0',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		file[80];
} mqd_HARDCOPY;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	channel;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_COMMAND;
 
#define mqh_COMMAND_INIT {0,20,'H',15,0,1,0,0,{'C','O','M','M','A','N','D',' '},5,{'S','[','4','0',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		command[40];
} mqd_COMMAND;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	channel;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_COMMANDR;
 
#define mqh_COMMANDR_INIT {0,20,'H',15,0,1,0,0,{'C','O','M','M','A','N','D','R'},5,{'S','[','4','0',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		command[40];
} mqd_COMMANDR;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	status;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_CREPLY;
 
#define mqh_CREPLY_INIT {0,25,'H',15,0,1,0,0,{'C','R','E','P','L','Y',' ',' '},5,{'S','[','8','0',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		reply[80];
} mqd_CREPLY;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	modify;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_NEWFILE;
 
#define mqh_NEWFILE_INIT {0,26,'H',15,0,3,0,0,{'N','E','W','F','I','L','E',' '},7,{'S','[','8','0',']','2','L',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		filename[80];
   int_4	arg1;
   int_4	arg2;
} mqd_NEWFILE;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	success;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_NEWFILEINFO;
 
#define mqh_NEWFILEINFO_INIT {0,26,'H',15,0,3,0,0,{'=','N','E','W','F','I','L','E'},7,{'S','[','8','0',']','2','L',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		filename[80];
   int_4	arg1;
   int_4	arg2;
} mqd_NEWFILEINFO;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_MODIFYINFO;
 
#define mqh_MODIFYINFO_INIT {0,18,'H',15,0,5,0,0,{'=','M','O','D','I','F','Y',' '},7,{'D','3','L','S','[','4',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   real_8	elemt;
   int_4	field;
   int_4	scalar;
   int_4	subelemt;
   char		name[4];
} mqd_MODIFYINFO;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_MODIFY;
 
#define mqh_MODIFY_INIT {0,18,'H',15,0,5,0,0,{'M','O','D','I','F','Y',' ',' '},7,{'D','3','L','S','[','4',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   real_8	elemt;
   int_4	field;
   int_4	scalar;
   int_4	subelemt;
   char		name[4];
} mqd_MODIFY;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_SELECTINFO;
 
#define mqh_SELECTINFO_INIT {0,18,'H',15,0,5,0,0,{'=','S','E','L','E','C','T',' '},7,{'D','3','L','S','[','4',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   real_8	elemt;
   int_4	field;
   int_4	scalar;
   int_4	subelemt;
   char		name[4];
} mqd_SELECTINFO;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	pan;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_SELECT;
 
#define mqh_SELECT_INIT {0,18,'H',15,0,5,0,0,{'S','E','L','E','C','T',' ',' '},7,{'D','3','L','S','[','4',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   real_8	elemt;
   int_4	field;
   int_4	scalar;
   int_4	subelemt;
   char		name[4];
} mqd_SELECT;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_LOOKUPINFO;
 
#define mqh_LOOKUPINFO_INIT {0,18,'H',15,0,5,0,0,{'=','L','O','O','K','U','P',' '},7,{'D','3','L','S','[','4',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   real_8	elemt;
   int_4	field;
   int_4	scalar;
   int_4	subelemt;
   char		name[4];
} mqd_LOOKUPINFO;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_LOOKUP;
 
#define mqh_LOOKUP_INIT {0,18,'H',15,0,5,0,0,{'L','O','O','K','U','P',' ',' '},7,{'D','3','L','S','[','4',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   real_8	elemt;
   int_4	field;
   int_4	scalar;
   int_4	subelemt;
   char		name[4];
} mqd_LOOKUP;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_HLITADD;
 
#define mqh_HLITADD_INIT {0,20,'H',15,0,8,0,0,{'H','L','I','T','A','D','D',' '},8,{'2','L','D','2','L','D','2','L',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   int_4	id;
   int_4	color;
   real_8	elemtfrom;
   int_4	fieldfrom;
   int_4	scalarfrom;
   real_8	elemtto;
   int_4	fieldto;
   int_4	scalarto;
} mqd_HLITADD;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	region;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_HLITMOD;
 
#define mqh_HLITMOD_INIT {0,20,'H',15,0,8,0,0,{'H','L','I','T','M','O','D',' '},8,{'2','L','D','2','L','D','2','L',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   int_4	id;
   int_4	color;
   real_8	elemtfrom;
   int_4	fieldfrom;
   int_4	scalarfrom;
   real_8	elemtto;
   int_4	fieldto;
   int_4	scalarto;
} mqd_HLITMOD;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	region;
   int_4	mode;
   char		name[8];
} mqh_HLITDEL;
 
#define mqh_HLITDEL_INIT {0,5,'L',4,0,1,0,0,{'H','L','I','T','D','E','L',' '}}
 
typedef struct
{
   int_4	id;
} mqd_HLITDEL;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	op;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_FEDIT;
 
#define mqh_FEDIT_INIT {0,17,'H',15,0,2,0,0,{'F','E','D','I','T',' ',' ',' '},2,{'D','L',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   real_8	elemt;
   int_4	numelemts;
} mqd_FEDIT;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	op;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_FEDITINFO;
 
#define mqh_FEDITINFO_INIT {0,17,'H',15,0,2,0,0,{'=','F','E','D','I','T',' ',' '},2,{'D','L',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   real_8	elemt;
   int_4	numelemts;
} mqd_FEDITINFO;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_XTEXT;
 
#define mqh_XTEXT_INIT {0,27,'H',15,0,1,0,0,{'X','T','E','X','T',' ',' ',' '},5,{'S','[','9','6',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		text[96];
} mqd_XTEXT;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_XTEXTA;
 
#define mqh_XTEXTA_INIT {0,27,'H',15,0,1,0,0,{'X','T','E','X','T','A',' ',' '},5,{'S','[','9','6',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		text[96];
} mqd_XTEXTA;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_XTEXTROW;
 
#define mqh_XTEXTROW_INIT {0,28,'H',15,0,3,0,0,{'X','T','E','X','T','R','O','W'},7,{'2','L','S','[','9','6',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   int_4	row;
   int_4	na;
   char		text[96];
} mqd_XTEXTROW;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_XTEXTCLR;
 
#define mqh_XTEXTCLR_INIT {0,27,'H',15,0,1,0,0,{'X','T','E','X','T','C','L','R'},5,{'S','[','9','6',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		text[96];
} mqd_XTEXTCLR;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_XTEXTHDR;
 
#define mqh_XTEXTHDR_INIT {0,27,'H',15,0,1,0,0,{'X','T','E','X','T','H','D','R'},5,{'S','[','9','6',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		text[96];
} mqd_XTEXTHDR;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
} mqh_XTCLEAR;
 
#define mqh_XTCLEAR_INIT {0,4,' ',4,0,0,0,0,{'X','T','C','L','E','A','R',' '}}
 
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
} mqh_XTXTRPOS;
 
#define mqh_XTXTRPOS_INIT {0,5,'L',4,0,2,0,0,{'X','T','X','T','R','P','O','S'}}
 
typedef struct
{
   int_4	row;
   int_4	position;
} mqd_XTXTRPOS;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	modmask;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_T5REC;
 
#define mqh_T5REC_INIT {0,27,'H',15,0,17,0,0,{'T','5','R','E','C',' ',' ',' '},10,{'2','L','3','D','A','6','D','L','4','B',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   int_4	layer;
   int_4	index;
   real_8	alt;
   real_8	lat;
   real_8	lon;
   char		name[8];
   real_8	azim;
   real_8	elev;
   real_8	roll;
   real_8	r;
   real_8	a;
   real_8	b;
   int_4	color;
   int_1	symbol;
   int_1	size;
   int_1	cone;
   int_1	invert;
} mqd_T5REC;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	modmask;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_T5TEXT;
 
#define mqh_T5TEXT_INIT {0,27,'H',15,0,12,0,0,{'T','5','T','E','X','T',' ',' '},13,{'2','L','3','D','A','S','[','4','8',']','L','4','B',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   int_4	layer;
   int_4	index;
   real_8	alt;
   real_8	lat;
   real_8	lon;
   char		name[8];
   char		text[48];
   int_4	color;
   int_1	symbol;
   int_1	size;
   int_1	cone;
   int_1	invert;
} mqd_T5TEXT;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	layer;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_T5LAYER;
 
#define mqh_T5LAYER_INIT {0,18,'H',15,0,5,0,0,{'T','5','L','A','Y','E','R',' '},3,{'A','4','L',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		action[8];
   int_4	p1;
   int_4	p2;
   int_4	p3;
   int_4	p4;
} mqd_T5LAYER;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_ATMRTDAT;
 
#define mqh_ATMRTDAT_INIT {0,18,'H',15,0,4,0,0,{'A','T','M','R','T','D','A','T'},4,{'2','D','2','L',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   real_8	time;
   real_8	y;
   int_4	colr;
   int_4	tnum;
} mqd_ATMRTDAT;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	num;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_ATMRTD8;
 
#define mqh_ATMRTD8_INIT {0,39,'H',15,0,32,0,0,{'A','T','M','R','T','D','8',' '},6,{'1','6','D','1','6','L',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   real_8	time1;
   real_8	time2;
   real_8	time3;
   real_8	time4;
   real_8	time5;
   real_8	time6;
   real_8	time7;
   real_8	time8;
   real_8	y1;
   real_8	y2;
   real_8	y3;
   real_8	y4;
   real_8	y5;
   real_8	y6;
   real_8	y7;
   real_8	y8;
   int_4	tnum1;
   int_4	tnum2;
   int_4	tnum3;
   int_4	tnum4;
   int_4	tnum5;
   int_4	tnum6;
   int_4	tnum7;
   int_4	tnum8;
   int_4	colr1;
   int_4	colr2;
   int_4	colr3;
   int_4	colr4;
   int_4	colr5;
   int_4	colr6;
   int_4	colr7;
   int_4	colr8;
} mqd_ATMRTD8;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	num;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_ATMRTD16;
 
#define mqh_ATMRTD16_INIT {0,63,'H',15,0,64,0,0,{'A','T','M','R','T','D','1','6'},12,{'1','6','D','1','6','L','1','6','D','1','6','L',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   real_8	time1;
   real_8	time2;
   real_8	time3;
   real_8	time4;
   real_8	time5;
   real_8	time6;
   real_8	time7;
   real_8	time8;
   real_8	y1;
   real_8	y2;
   real_8	y3;
   real_8	y4;
   real_8	y5;
   real_8	y6;
   real_8	y7;
   real_8	y8;
   int_4	tnum1;
   int_4	tnum2;
   int_4	tnum3;
   int_4	tnum4;
   int_4	tnum5;
   int_4	tnum6;
   int_4	tnum7;
   int_4	tnum8;
   int_4	colr1;
   int_4	colr2;
   int_4	colr3;
   int_4	colr4;
   int_4	colr5;
   int_4	colr6;
   int_4	colr7;
   int_4	colr8;
   real_8	time9;
   real_8	time10;
   real_8	time11;
   real_8	time12;
   real_8	time13;
   real_8	time14;
   real_8	time15;
   real_8	time16;
   real_8	y9;
   real_8	y10;
   real_8	y11;
   real_8	y12;
   real_8	y13;
   real_8	y14;
   real_8	y15;
   real_8	y16;
   int_4	tnum9;
   int_4	tnum10;
   int_4	tnum11;
   int_4	tnum12;
   int_4	tnum13;
   int_4	tnum14;
   int_4	tnum15;
   int_4	tnum16;
   int_4	colr9;
   int_4	colr10;
   int_4	colr11;
   int_4	colr12;
   int_4	colr13;
   int_4	colr14;
   int_4	colr15;
   int_4	colr16;
} mqd_ATMRTD16;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_ATMOVER;
 
#define mqh_ATMOVER_INIT {0,32,'H',15,0,7,0,0,{'A','T','M','O','V','E','R',' '},13,{'D','4','L','S','[','8','0',']','S','[','3','2',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   real_8	connect;
   int_4	colr;
   int_4	refresh;
   int_4	mode;
   int_4	sect;
   char		name[80];
   char		dispname[32];
} mqd_ATMOVER;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_ATMDOVER;
 
#define mqh_ATMDOVER_INIT {0,26,'H',15,0,3,0,0,{'A','T','M','D','O','V','E','R'},7,{'2','L','S','[','8','0',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   int_4	refresh;
   int_4	sect;
   char		name[80];
} mqd_ATMDOVER;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_NEWTRACE;
 
#define mqh_NEWTRACE_INIT {0,29,'H',15,0,8,0,0,{'N','E','W','T','R','A','C','E'},8,{'6','L','A','S','[','8','0',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   int_4	tnum;
   int_4	bufsize;
   int_4	mode;
   int_4	sect;
   int_4	size;
   int_4	colr;
   char		datatype[8];
   char		name[80];
} mqd_NEWTRACE;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_DELTRACE;
 
#define mqh_DELTRACE_INIT {0,26,'H',15,0,3,0,0,{'D','E','L','T','R','A','C','E'},7,{'2','L','S','[','8','0',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   int_4	tnum;
   int_4	refresh;
   char		name[80];
} mqd_DELTRACE;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
} mqh_ICONIFY;
 
#define mqh_ICONIFY_INIT {0,4,' ',4,0,0,0,0,{'I','C','O','N','I','F','Y',' '}}
 
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
} mqh_DEICON;
 
#define mqh_DEICON_INIT {0,4,' ',4,0,0,0,0,{'D','E','I','C','O','N',' ',' '}}
 
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_THRESH;
 
#define mqh_THRESH_INIT {0,19,'H',15,0,7,0,0,{'T','H','R','E','S','H',' ',' '},3,{'D','6','L',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   real_8	level;
   int_4	thick;
   int_4	sect;
   int_4	num;
   int_4	colr;
   int_4	refresh;
   int_4	dummy;
} mqd_THRESH;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
} mqh_TSTATE;
 
#define mqh_TSTATE_INIT {0,6,'L',4,0,4,0,0,{'T','S','T','A','T','E',' ',' '}}
 
typedef struct
{
   int_4	sect;
   int_4	num;
   int_4	state;
   int_4	refresh;
} mqd_TSTATE;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_YAXIS;
 
#define mqh_YAXIS_INIT {0,19,'H',15,0,6,0,0,{'Y','A','X','I','S',' ',' ',' '},4,{'2','D','4','L',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   real_8	ymin;
   real_8	ymax;
   int_4	sect;
   int_4	ydiv;
   int_4	origin;
   int_4	dummy;
} mqd_YAXIS;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_TRNAME;
 
#define mqh_TRNAME_INIT {0,26,'H',15,0,3,0,0,{'T','R','N','A','M','E',' ',' '},7,{'2','L','S','[','8','0',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   int_4	tnum;
   int_4	dummy;
   char		name[80];
} mqd_TRNAME;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	num;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_TRNAME8;
 
#define mqh_TRNAME8_INIT {0,99,'H',15,0,16,0,0,{'T','R','N','A','M','E','8',' '},8,{'8','L','8','S','[','8','0',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   int_4	tnum1;
   int_4	tnum2;
   int_4	tnum3;
   int_4	tnum4;
   int_4	tnum5;
   int_4	tnum6;
   int_4	tnum7;
   int_4	tnum8;
   char		name1[80];
   char		name2[80];
   char		name3[80];
   char		name4[80];
   char		name5[80];
   char		name6[80];
   char		name7[80];
   char		name8[80];
} mqd_TRNAME8;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_TIMEADJ;
 
#define mqh_TIMEADJ_INIT {0,17,'H',15,0,5,0,0,{'T','I','M','E','A','D','J',' '},5,{'F','2','I','2','L',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   real_4	adjust;
   int_2	sect;
   int_2	colr;
   int_4	refresh;
   int_4	dummy;
} mqd_TIMEADJ;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
} mqh_ATMDIFF;
 
#define mqh_ATMDIFF_INIT {0,5,'F',4,0,1,0,0,{'A','T','M','D','I','F','F',' '}}
 
typedef struct
{
   real_4	diff;
} mqd_ATMDIFF;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
} mqh_CLEAR;
 
#define mqh_CLEAR_INIT {0,4,' ',4,0,0,0,0,{'C','L','E','A','R',' ',' ',' '}}
 
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_SETKEY;
 
#define mqh_SETKEY_INIT {0,30,'H',15,0,3,0,0,{'S','E','T','K','E','Y',' ',' '},6,{'3','S','[','4','0',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		addr[40];
   char		name[40];
   char		value[40];
} mqd_SETKEY;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_ACKKEY;
 
#define mqh_ACKKEY_INIT {0,30,'H',15,0,3,0,0,{'A','C','K','K','E','Y',' ',' '},6,{'3','S','[','4','0',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		addr[40];
   char		name[40];
   char		value[40];
} mqd_ACKKEY;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_GETKEY;
 
#define mqh_GETKEY_INIT {0,30,'H',15,0,3,0,0,{'G','E','T','K','E','Y',' ',' '},6,{'3','S','[','4','0',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		addr[40];
   char		name[40];
   char		value[40];
} mqd_GETKEY;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_RETKEY;
 
#define mqh_RETKEY_INIT {0,30,'H',15,0,3,0,0,{'R','E','T','K','E','Y',' ',' '},6,{'3','S','[','4','0',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		addr[40];
   char		name[40];
   char		value[40];
} mqd_RETKEY;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_RPKT;
 
#define mqh_RPKT_INIT {0,37,'H',15,0,3,0,0,{'R','P','K','T',' ',' ',' ',' '},15,{'S','[','4','0',']','S','[','8',']','S','[','1','2','8',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		addr[40];
   char		func[8];
   char		data[128];
} mqd_RPKT;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_RERR;
 
#define mqh_RERR_INIT {0,47,'H',15,0,4,0,0,{'R','E','R','R',' ',' ',' ',' '},20,{'S','[','8','0',']','S','[','4','0',']','S','[','8',']','S','[','1','2','8',']',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		text[80];
   char		addr[40];
   char		func[8];
   char		data[128];
} mqd_RERR;
 
typedef struct
{
   int_4	reader;
   int_2	nslots;
   char		type;
   int_1	nhslots;
   int_4	sender;
   int_4	ndata;
   int_4	info;
   int_4	mode;
   char		name[8];
   int_2	ntype;
   char		types[86];
} mqh_DISPCOLR;
 
#define mqh_DISPCOLR_INIT {0,22,'H',15,0,4,0,0,{'D','I','S','P','C','O','L','R'},7,{'S','[','4','0',']','3','L',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' ',' '}} 
 
typedef struct
{
   char		label[40];
   int_4	icd;
   int_4	icv;
   int_4	blink;
} mqd_DISPCOLR;
 
#define L_mqh 120
#define L_mqd 8192
 
typedef struct
{
   union
   {
      mqd_MSGLOG	MSGLOG;
      mqd_XMSG		XMSG;
      mqd_TITLE		TITLE;
      mqd_MSGMASK	MSGMASK;
      mqd_MSGMASKINFO	MSGMASKINFO;
      mqd_SET		SET;
      mqd_SETL		SETL;
      mqd_SETD		SETD;
      mqd_QUERY		QUERY;
      mqd_COLOR		COLOR;
      mqd_COLORINFO	COLORINFO;
      mqd_COLORMAP	COLORMAP;
      mqd_COLORMAPINFO	COLORMAPINFO;
      mqd_TRACE		TRACE;
      mqd_OVERLAY	OVERLAY;
      mqd_DEOVERLAY	DEOVERLAY;
      mqd_TRIM		TRIM;
      mqd_CXMODE	CXMODE;
      mqd_CXMODEINFO	CXMODEINFO;
      mqd_ZOOM		ZOOM;
      mqd_ZOOMINFO	ZOOMINFO;
      mqd_UNZOOMINFO	UNZOOMINFO;
      mqd_PAN		PAN;
      mqd_PANRANGE	PANRANGE;
      mqd_PANINFO	PANINFO;
      mqd_PLOTINFO	PLOTINFO;
      mqd_MARKINFO	MARKINFO;
      mqd_MARK		MARK;
      mqd_ANNOTATE	ANNOTATE;
      mqd_BOXINFO	BOXINFO;
      mqd_BOXADD	BOXADD;
      mqd_BOXALTER	BOXALTER;
      mqd_POINTINFO	POINTINFO;
      mqd_POINTADD	POINTADD;
      mqd_POINTALTER	POINTALTER;
      mqd_XCNTRL	XCNTRL;
      mqd_XCTAG		XCTAG;
      mqd_XTODO		XTODO;
      mqd_HARDCOPY	HARDCOPY;
      mqd_COMMAND	COMMAND;
      mqd_COMMANDR	COMMANDR;
      mqd_CREPLY	CREPLY;
      mqd_NEWFILE	NEWFILE;
      mqd_NEWFILEINFO	NEWFILEINFO;
      mqd_MODIFYINFO	MODIFYINFO;
      mqd_MODIFY	MODIFY;
      mqd_SELECTINFO	SELECTINFO;
      mqd_SELECT	SELECT;
      mqd_LOOKUPINFO	LOOKUPINFO;
      mqd_LOOKUP	LOOKUP;
      mqd_HLITADD	HLITADD;
      mqd_HLITMOD	HLITMOD;
      mqd_HLITDEL	HLITDEL;
      mqd_FEDIT		FEDIT;
      mqd_FEDITINFO	FEDITINFO;
      mqd_XTEXT		XTEXT;
      mqd_XTEXTA	XTEXTA;
      mqd_XTEXTROW	XTEXTROW;
      mqd_XTEXTCLR	XTEXTCLR;
      mqd_XTEXTHDR	XTEXTHDR;
      mqd_XTXTRPOS	XTXTRPOS;
      mqd_T5REC		T5REC;
      mqd_T5TEXT	T5TEXT;
      mqd_T5LAYER	T5LAYER;
      mqd_ATMRTDAT	ATMRTDAT;
      mqd_ATMRTD8	ATMRTD8;
      mqd_ATMRTD16	ATMRTD16;
      mqd_ATMOVER	ATMOVER;
      mqd_ATMDOVER	ATMDOVER;
      mqd_NEWTRACE	NEWTRACE;
      mqd_DELTRACE	DELTRACE;
      mqd_THRESH	THRESH;
      mqd_TSTATE	TSTATE;
      mqd_YAXIS		YAXIS;
      mqd_TRNAME	TRNAME;
      mqd_TRNAME8	TRNAME8;
      mqd_TIMEADJ	TIMEADJ;
      mqd_ATMDIFF	ATMDIFF;
      mqd_SETKEY	SETKEY;
      mqd_ACKKEY	ACKKEY;
      mqd_GETKEY	GETKEY;
      mqd_RETKEY	RETKEY;
      mqd_RPKT		RPKT;
      mqd_RERR		RERR;
      mqd_DISPCOLR	DISPCOLR;
      int_1		bbuf[L_mqd];
      int_2		ibuf[L_mqd/2];
      int_4		lbuf[L_mqd/4];
      real_4		fbuf[L_mqd/4];
      real_8		dbuf[L_mqd/8];
      char		abuf[L_mqd];
      char		sbuf[L_mqd];
   } MQD_UNION;
#ifdef __cplusplus
} MQ_DATA;
#else
} mq_DATA;
#endif
 
#define XM_QMESSDEF_H_
#endif /* XM_QMESSDEF_H_ */
