(custom-set-variables
 '(ps-postscript-code-directory "/usr/share/emacs/21.3/etc")
 '(column-number-mode t)
 '(bar-cursor 2)
 '(make-backup-files nil)
 '(ps-print-color-p nil)
 '(toolbar-print-function (quote ps-print-buffer-with-faces))
 '(line-number-mode t)
 '(compile-command "make")
 '(dialog-frame-plist (quote (width 80 height 40)))
 '(blink-cursor-mode t nil (blink-cursor))
 '(user-mail-address "bergman@localhost.localdomain")
 '(query-user-mail-address nil))

(custom-set-faces
 '(modeline ((t (:background "light grey"))) t)
 '(default ((t (:background "light grey" :size "12pt"))) t)
 '(dired-face-directory ((((class color) (background light))         (:foreground "black"     :bold t   :italic nil :underline nil))))
 '(font-lock-string-face ((((class color) (background light))        (:foreground "DarkGreen" :bold nil :italic nil :underline nil))))
 '(font-lock-reference-face ((((class color) (background light))     (:foreground "DarkGreen" :bold nil :italic nil :underline nil))))
 '(font-lock-doc-string-face ((((class color) (background light))    (:foreground "DarkGreen" :bold nil :italic nil :underline nil))))
 '(font-lock-preprocessor-face ((((class color) (background light))  (:foreground "DarkBlue"  :bold nil :italic nil :underline nil))))
 '(font-lock-variable-name-face ((((class color) (background light)) (:foreground "DarkGreen" :bold nil :italic nil :underline nil))))
 '(font-lock-keyword-face ((((class color) (background light))       (:foreground "DarkGreen" :bold nil :italic nil :underline nil))))
 '(font-lock-builtin-face ((((class color) (background light))       (:foreground "DarkGreen" :bold nil :italic nil :underline nil))))
 '(font-lock-type-face ((((class color) (background light))          (:foreground "DarkBlue"  :bold nil :italic nil :underline nil))))
 '(font-lock-face-list ((((class color) (background light))          (:foreground "green"     :bold nil :italic nil :underline nil))))
 '(font-lock-comment-face ((((class color) (background light))       (:foreground "red"       :bold t   :italic nil :underline nil))))
 '(dired-face-executable ((((class color) (background light))        (:foreground "SlateGray" :bold t   :italic nil :underline nil))))
 '(font-lock-function-name-face ((((class color) (background light)) (:foreground "DarkGreen" :bold nil :italic nil :underline nil))))
 '(isearch ((((class color) (background light))  (:background "white" :foreground "black"     :bold nil :italic nil :underline nil))))
 '(dired-face-symlink ((((class color) (background light))           (:foreground "blue"      :bold t   :italic nil :underline nil))))
 '(dired-face-boring ((((class color) (background light))            (:foreground "red"       :bold t   :italic nil :underline nil))))
)

;;(custom-set-faces
;; '(modeline ((t (:background "light grey"))) t)
;; '(default ((t (:background "light grey" :size "12pt"))) t)
;; '(dired-face-directory ((((class color) (background light))         (:foreground "black"     :bold t   :italic nil :underline nil))))
;; '(font-lock-string-face ((((class color) (background light))        (:foreground "DarkGreen" :bold nil :italic nil :underline nil))))
;; '(font-lock-reference-face ((((class color) (background light))     (:foreground "DarkGreen" :bold nil :italic nil :underline nil))))
;; '(font-lock-doc-string-face ((((class color) (background light))    (:foreground "DarkGreen" :bold nil :italic nil :underline nil))))
;; '(font-lock-preprocessor-face ((((class color) (background light))  (:foreground "DarkBlue"  :bold nil :italic nil :underline nil))))
;; '(font-lock-variable-name-face ((((class color) (background light)) (:foreground "DarkGreen" :bold nil :italic nil :underline nil))))
;; '(font-lock-keyword-face ((((class color) (background light))       (:foreground "DarkGreen" :bold nil :italic nil :underline nil))))
;; '(font-lock-builtin-face ((((class color) (background light))       (:foreground "DarkGreen" :bold nil :italic nil :underline nil))))
;; '(font-lock-type-face ((((class color) (background light))          (:foreground "DarkBlue"  :bold nil :italic nil :underline nil))))
;; '(font-lock-face-list ((((class color) (background light))          (:foreground "green"     :bold nil :italic nil :underline nil))))
;; '(font-lock-comment-face ((((class color) (background light))       (:foreground "red"       :bold t   :italic nil :underline nil))))
;; '(dired-face-executable ((((class color) (background light))        (:foreground "SlateGray" :bold t   :italic nil :underline nil))))
;; '(font-lock-function-name-face ((((class color) (background light)) (:foreground "DarkGreen" :bold nil :italic nil :underline nil))))
;; '(isearch ((((class color) (background light))  (:background "white" :foreground "black"     :bold nil :italic nil :underline nil))))
;; '(dired-face-symlink ((((class color) (background light))           (:foreground "blue"      :bold t   :italic nil :underline nil))))
;; '(dired-face-boring ((((class color) (background light))            (:foreground "red"       :bold t   :italic nil :underline nil))))
;;)



