#!/bin/sh
# This script runs the common code preprocessor.
#------------------------------------------------------------------------------------------------
if [ "$1" == "-i" ]; then                           # Check for "inline" flag
  perl -i $XMOPTS/xmc/dev/perlCommonCode $2;        # Use with    "-i" to make changes.
else                                                # Else
  perl    $XMOPTS/xmc/dev/perlCommonCode $1;        # Use without "-i" to test.
fi
